version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/_db_init:/docker-entrypoint-initdb.d
    env_file: .env.dev
  adminer:
    image: adminer
    ports:
      - 8090:8080
    depends_on:
      - postgres

volumes:
  db_data:
